package com.restaurant;

import AppPackage.AnimationClass;
import com.restaurant.Manger_Calsses.Manager;
import com.restaurant.Manger_GUI.managerlayout;
import com.restaurant.User_GUI.log_reg;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.animation.Animation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a
 */
public class Login extends javax.swing.JFrame {
AnimationClass ac = new AnimationClass();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
       // SlideShow();
        user.setBackground(new java.awt.Color(0,0,0,1));
        pass.setBackground(new java.awt.Color(0,0,0,1));
    }

    public void SlideShow()
    {
        new Thread(new Runnable() {
            int count = 0;
            @Override
            public void run() {
                try{
                    while(true){
                        switch(count){

                            case 0:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(0, -1080, 20, 10, hambrg);
                                ac.jLabelXLeft(1080, 0, 20, 10, chinese);
                                count++;
                                break;
                             case 1:
                                Thread.sleep(3000);
                                ac.jLabelXRight(-1080, 0, 20, 10, choco2);
                                ac.jLabelXRight(0, 1080, 20, 10, chinese);
                                count++;
                                break;
                            case 2:
                                Thread.sleep(3000);
                                ac.jLabelYUp(0, -620, 20, 10, choco2);
                                ac.jLabelYUp(620, 0, 20, 10, choco);
                                count++;
                                break;
                            case 3:
                                Thread.sleep(3000);
                                ac.jLabelYDown(0, 620, 20, 10, choco);
                                ac.jLabelYDown(-620, 0, 20, 10, rest);
                                count++;
                                break;
                        }
                    }
                }
                catch(Exception e){

                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EXIT = new keeptoo.KButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        Login = new keeptoo.KButton();
        rest = new javax.swing.JLabel();
        choco = new javax.swing.JLabel();
        choco2 = new javax.swing.JLabel();
        chinese = new javax.swing.JLabel();
        hambrg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 620));
        getContentPane().setLayout(null);

        EXIT.setBorder(null);
        EXIT.setText("EXIT");
        EXIT.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        EXIT.setkBorderRadius(30);
        EXIT.setkEndColor(new java.awt.Color(255, 51, 0));
        EXIT.setkHoverEndColor(new java.awt.Color(102, 102, 0));
        EXIT.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EXIT.setkHoverStartColor(new java.awt.Color(51, 0, 0));
        EXIT.setkIndicatorThickness(0);
        EXIT.setkSelectedColor(new java.awt.Color(153, 0, 0));
        EXIT.setkStartColor(new java.awt.Color(0, 0, 0));
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT);
        EXIT.setBounds(970, 10, 90, 40);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 220, 110, 14);

        user.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        user.setOpaque(false);
        jPanel1.add(user);
        user.setBounds(70, 150, 230, 30);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 110, 14);

        pass.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pass.setOpaque(false);
        jPanel1.add(pass);
        pass.setBounds(70, 260, 230, 30);

        Login.setBorder(null);
        Login.setText("Log In");
        Login.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        Login.setkBorderRadius(30);
        Login.setkEndColor(new java.awt.Color(255, 51, 0));
        Login.setkHoverEndColor(new java.awt.Color(102, 102, 0));
        Login.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Login.setkHoverStartColor(new java.awt.Color(51, 0, 0));
        Login.setkIndicatorThickness(0);
        Login.setkSelectedColor(new java.awt.Color(153, 0, 0));
        Login.setkStartColor(new java.awt.Color(0, 0, 0));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(90, 370, 130, 45);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 80, 320, 470);

        rest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(rest);
        rest.setBounds(0, -620, 1080, 620);

        choco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/choco.jpg"))); // NOI18N
        getContentPane().add(choco);
        choco.setBounds(0, 620, 1080, 620);

        choco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/choco2.jpg"))); // NOI18N
        getContentPane().add(choco2);
        choco2.setBounds(-1080, 0, 1080, 620);

        chinese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chinese.jpg"))); // NOI18N
        getContentPane().add(chinese);
        chinese.setBounds(1080, 0, 1080, 620);

        hambrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Fast_food_Hamburger_Vegetables_Fire_Two_520128_1920x1080.jpg"))); // NOI18N
        getContentPane().add(hambrg);
        hambrg.setBounds(0, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

        
            Manager m = new Manager();
        String casee = m.login(user.getText(), pass.getText());
        if (casee.equals("true"))
        {
            JOptionPane.showMessageDialog(this, "Done");
            managerlayout managerwindow=new managerlayout();
            managerwindow.show();
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        else if (casee.equals("user"))
        {
            JOptionPane.showMessageDialog(this, "username is un correct");
        }
        else if (casee.equals("pass+user"))
        {
            JOptionPane.showMessageDialog(this, "username and password is un correct");
        }
        else if (casee.equals("pass"))
        {
            JOptionPane.showMessageDialog(this, "password is un correct");
        }
        else if (casee.equals("empty"))
        {
            JOptionPane.showMessageDialog(this, "there are an empty field");
        }
        
    }//GEN-LAST:event_LoginActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        this.dispose();
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton EXIT;
    private keeptoo.KButton Login;
    private javax.swing.JLabel chinese;
    private javax.swing.JLabel choco;
    private javax.swing.JLabel choco2;
    private javax.swing.JLabel hambrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pass;
    private javax.swing.JLabel rest;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
