/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.User_GUI;

import com.restaurant.User_Classes.Bill;
import javax.swing.BoxLayout;

/**
 *
 * @author com
 */
public class bill2 extends java.awt.Panel {

    /**
     * Creates new form bill2
     */
    public bill2() {
        initComponents();
            for(int i=0;i<Bill.getItem().size();i++)
        {
        order_item o=new order_item();
        o.getjLabel4().setText(Bill.getItem().get(i).getName());
        o.getjLabel5().setText(String.valueOf(Bill.getItem().get(i).getPrice()));
        o.getjLabel6().setText(String.valueOf(Bill.getItem().get(i).getPormotion().getDiscount()));
        o.getjLabel8().setText(String.valueOf(Bill.getItem().get(i).getIntquantity_in_bill()));
        this.setLayout(new BoxLayout(this,BoxLayout.PAGE_AXIS));
        this.add(o);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
