/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.User_GUI;

import com.restaurant.User_Classes.Bill;
import com.restaurant.User_Classes.order;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author com
 */
public class messege_complain extends javax.swing.JFrame {

    /**
     * Creates new form messege_complain
     */
    Bill b=new Bill();

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }
            
    public messege_complain() {
        initComponents();
        jTextField1.setBackground(new java.awt.Color(0,0,0,1));
        jTextField2.setBackground(new java.awt.Color(0,0,0,1));
        this.setLocationRelativeTo(null);
        //this.setBackground(Color.RED);
     //  jLabel4.setVisible(false);
       jLabel5.setVisible(false);
        b.Total_Cashe();
        b.MakeDiscount();
        b.dlivery_boy();
        jTextField1.setText(String.valueOf(b.getTotalCashe()));
        if(b. getTotalCasheAfterPormortion()<=0)
        {
           // jLabel4.setVisible(true);
             jLabel5.setVisible(true);}
        else
        jTextField2.setText(String.valueOf(b. getTotalCasheAfterPormortion()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ok = new keeptoo.KButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(520, 445));
        setMinimumSize(new java.awt.Dimension(520, 445));
        setUndecorated(true);
        setSize(new java.awt.Dimension(520, 445));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Total cash");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 123, 27);

        ok.setBorder(null);
        ok.setText("OK");
        ok.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        ok.setkBorderRadius(30);
        ok.setkEndColor(new java.awt.Color(255, 51, 0));
        ok.setkHoverEndColor(new java.awt.Color(102, 102, 0));
        ok.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ok.setkHoverStartColor(new java.awt.Color(51, 0, 0));
        ok.setkIndicatorThickness(0);
        ok.setkSelectedColor(new java.awt.Color(153, 0, 0));
        ok.setkStartColor(new java.awt.Color(0, 0, 0));
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(190, 400, 110, 40);

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 60, 217, 27);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Total cash after pormotion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 204, 27);

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 120, 217, 27);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("       write your complain");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 230, 185, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 460, 100);

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("You take it free");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 180, 181, 27);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mccain-fries-and-appetizers.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(520, 445));
        jLabel4.setMinimumSize(new java.awt.Dimension(520, 445));
        jLabel4.setPreferredSize(new java.awt.Dimension(520, 445));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 520, 445);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        order o=new order(jTextArea1.getText(),b);
       o.add_order();
       this.setVisible(false);
       Bill.clear();
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messege_complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messege_complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messege_complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messege_complain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messege_complain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private keeptoo.KButton ok;
    // End of variables declaration//GEN-END:variables
}
