/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.User_GUI;

import com.restaurant.helper;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Mayar khaled
 */
public class special_offers extends javax.swing.JFrame {

    /**
     * Creates new form special_offers
     */
    public special_offers() {
        initComponents();
        this.setLocationRelativeTo(null);
         //jPanel1.setLayout(new BoxLayout(jPanel1,BoxLayout.PAGE_AXIS));
         //JScrollPane pane = new JScrollPane(jPanel1);
         
          helper.startConnection();
          try{
          
            String query = "SELECT * FROM announcement";
           helper.dBResult = helper.stmt.executeQuery(query);
            while(helper.dBResult.next())
            { System.out.print("hh");
                special_offers_item item = new special_offers_item();
                item.setjLabel2(helper.dBResult.getString("ann_name"));
                item.setjLabel4(helper.dBResult.getString("ann_end_date"));
                item.setjLabel6(helper.dBResult.getString("ann_items_names"));
                item.setjLabel8(helper.dBResult.getString("ann_price"));
                item.setjLabel10(helper.dBResult.getString("ann_message"));
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM");  
                     Date date = new Date();  
                 String current_day = formatter.format(date);
                 int day, month ;
                 char d = current_day.charAt(0);
                 char dd = current_day.charAt(1);
                 day =Integer.parseInt(d+""+dd);
                 char m = current_day.charAt(3);
                 char mm = current_day.charAt(4);
                 month =Integer.parseInt(m+""+mm);
                 
                 String end_Date = item.getjLabel4().getText();
                 int day2, month2;
                 char d2 = end_Date.charAt(0);
                 char dd2 = end_Date.charAt(1);
                 day2 =Integer.parseInt(d2+""+dd2);
                 char m2 = end_Date.charAt(3);
                 char mm2 = end_Date.charAt(4);
                 month2 = Integer.parseInt(m2+""+mm2);
               /*  if(day > day2 && month >= month2)
                     continue;*/
                //pane.add(item);
                jTabbedPane1.add(item.getjLabel2().getText(),item);
            }
          }
           catch(NumberFormatException | SQLException ex)
         {
             System.out.println(ex.getMessage());
         }
         finally{
         helper.close();
          }
    // this.pack();
     //this.getContentPane().add(pane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        close = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        close.setBorder(null);
        close.setText("CLOSE");
        close.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        close.setkBorderRadius(30);
        close.setkEndColor(new java.awt.Color(255, 51, 0));
        close.setkHoverEndColor(new java.awt.Color(102, 102, 0));
        close.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        close.setkHoverStartColor(new java.awt.Color(51, 0, 0));
        close.setkIndicatorThickness(0);
        close.setkSelectedColor(new java.awt.Color(153, 0, 0));
        close.setkStartColor(new java.awt.Color(0, 0, 0));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(special_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(special_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(special_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(special_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new special_offers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton close;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
