/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.Manger_GUI;

import AppPackage.AnimationClass;
import com.restaurant.Manger_Calsses.Manager;
import com.restaurant.Manger_GUI.add_pormationform;
import com.restaurant.Manger_Calsses.Pormotion;
import com.restaurant.Manger_Calsses.InventoryItem;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmo
 */
public class additemform extends javax.swing.JFrame {

AnimationClass ac = new AnimationClass();
ArrayList<InventoryItem> itemslist=new ArrayList<InventoryItem>();
byte[] itemimg;
static String state="withoutpormotion";
Icon defaltimg;
static Pormotion p;

    public additemform() {
        initComponents();
       defaltimg=imgLBL.getIcon();
       this.setLocationRelativeTo(null);
       //SlideShow();
       CatNameTX2.setBackground(new java.awt.Color(0,0,0,1));
       i_idTX.setBackground(new java.awt.Color(0,0,0,1));
       i_nameTX.setBackground(new java.awt.Color(0,0,0,1));
       i_priceTX.setBackground(new java.awt.Color(0,0,0,1));
       i_quantiyTX.setBackground(new java.awt.Color(0,0,0,1));
    }
public static  void getpo(Pormotion p)
{
    additemform.p=p;
}

public static void setstat(String st)
{
    state=st;
}
 public void SlideShow()
{
    new Thread(new Runnable() {
            int count = 0;
            @Override
            public void run() {
                try{
                    while(true){
                        switch(count){
                            
                            case 0:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(0, -1080, 20, 10, jLabel3);
                                count++;
                                break;
                        }
                    }
                }
                catch(Exception e){
                    
                }
            }
        }).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        CatNameTX2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        i_idTX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        i_nameTX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        i_priceTX = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        i_quantiyTX = new javax.swing.JTextField();
        ADD_ITEM_B = new keeptoo.KButton();
        imgLBL = new javax.swing.JLabel();
        choiceimgB = new keeptoo.KButton();
        backtomenuB = new keeptoo.KButton();
        add_porB = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 250));
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 620));
        setSize(new java.awt.Dimension(1080, 620));
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Category");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 80, 81, 23);

        CatNameTX2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        CatNameTX2.setForeground(new java.awt.Color(255, 255, 255));
        CatNameTX2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        CatNameTX2.setOpaque(false);
        getContentPane().add(CatNameTX2);
        CatNameTX2.setBounds(130, 80, 200, 30);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 30, 23);

        i_idTX.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        i_idTX.setForeground(new java.awt.Color(255, 255, 255));
        i_idTX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        i_idTX.setOpaque(false);
        getContentPane().add(i_idTX);
        i_idTX.setBounds(130, 130, 200, 30);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(26, 182, 49, 23);

        i_nameTX.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        i_nameTX.setForeground(new java.awt.Color(255, 255, 255));
        i_nameTX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        i_nameTX.setOpaque(false);
        getContentPane().add(i_nameTX);
        i_nameTX.setBounds(129, 180, 200, 30);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(26, 230, 50, 23);

        i_priceTX.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        i_priceTX.setForeground(new java.awt.Color(255, 255, 255));
        i_priceTX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        i_priceTX.setOpaque(false);
        i_priceTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_priceTXActionPerformed(evt);
            }
        });
        getContentPane().add(i_priceTX);
        i_priceTX.setBounds(129, 228, 200, 30);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(26, 289, 80, 23);

        i_quantiyTX.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        i_quantiyTX.setForeground(new java.awt.Color(255, 255, 255));
        i_quantiyTX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        i_quantiyTX.setOpaque(false);
        getContentPane().add(i_quantiyTX);
        i_quantiyTX.setBounds(129, 287, 200, 30);

        ADD_ITEM_B.setBorder(null);
        ADD_ITEM_B.setText("ADD");
        ADD_ITEM_B.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        ADD_ITEM_B.setkBackGroundColor(new java.awt.Color(0, 102, 102));
        ADD_ITEM_B.setkBorderRadius(30);
        ADD_ITEM_B.setkEndColor(new java.awt.Color(0, 0, 0));
        ADD_ITEM_B.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        ADD_ITEM_B.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ADD_ITEM_B.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        ADD_ITEM_B.setkIndicatorThickness(0);
        ADD_ITEM_B.setkSelectedColor(new java.awt.Color(102, 51, 0));
        ADD_ITEM_B.setkStartColor(new java.awt.Color(0, 102, 102));
        ADD_ITEM_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_ITEM_BActionPerformed(evt);
            }
        });
        getContentPane().add(ADD_ITEM_B);
        ADD_ITEM_B.setBounds(30, 520, 482, 45);

        imgLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hamburger.png"))); // NOI18N
        imgLBL.setToolTipText("");
        imgLBL.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgLBL.setOpaque(true);
        imgLBL.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(imgLBL);
        imgLBL.setBounds(380, 150, 128, 128);

        choiceimgB.setBorder(null);
        choiceimgB.setText("choice image");
        choiceimgB.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        choiceimgB.setkBackGroundColor(new java.awt.Color(0, 102, 102));
        choiceimgB.setkBorderRadius(30);
        choiceimgB.setkEndColor(new java.awt.Color(0, 0, 0));
        choiceimgB.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        choiceimgB.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        choiceimgB.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        choiceimgB.setkIndicatorThickness(0);
        choiceimgB.setkSelectedColor(new java.awt.Color(102, 51, 0));
        choiceimgB.setkStartColor(new java.awt.Color(0, 102, 102));
        choiceimgB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceimgBActionPerformed(evt);
            }
        });
        getContentPane().add(choiceimgB);
        choiceimgB.setBounds(350, 310, 185, 45);

        backtomenuB.setBorder(null);
        backtomenuB.setText("BACK");
        backtomenuB.setkBackGroundColor(new java.awt.Color(0, 102, 102));
        backtomenuB.setkBorderRadius(0);
        backtomenuB.setkEndColor(new java.awt.Color(0, 0, 0));
        backtomenuB.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        backtomenuB.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        backtomenuB.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        backtomenuB.setkIndicatorThickness(0);
        backtomenuB.setkSelectedColor(new java.awt.Color(102, 51, 0));
        backtomenuB.setkStartColor(new java.awt.Color(0, 102, 102));
        backtomenuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomenuBActionPerformed(evt);
            }
        });
        getContentPane().add(backtomenuB);
        backtomenuB.setBounds(0, 0, 60, 30);

        add_porB.setBorder(null);
        add_porB.setText("ADD pormotion");
        add_porB.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        add_porB.setkBackGroundColor(new java.awt.Color(0, 102, 102));
        add_porB.setkBorderRadius(30);
        add_porB.setkEndColor(new java.awt.Color(0, 0, 0));
        add_porB.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        add_porB.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        add_porB.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        add_porB.setkIndicatorThickness(0);
        add_porB.setkSelectedColor(new java.awt.Color(102, 51, 0));
        add_porB.setkStartColor(new java.awt.Color(0, 102, 102));
        add_porB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_porBActionPerformed(evt);
            }
        });
        getContentPane().add(add_porB);
        add_porB.setBounds(30, 360, 260, 45);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/food-table-relisted.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1080, 620);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/brands-and-products-small.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 0, 540, 620);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dark-red-wallpaper-hd-10503330.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//String itemcode, String name, float rank, double price, byte[] photo, int quantity, Pormotion pormotion,String catName
    private void ADD_ITEM_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_ITEM_BActionPerformed

        Manager manager = new Manager();
    
//  System.out.println(p1.getId());
        
      InventoryItem item=null;
        if(state.equals("withpormotion"))
         {
            item=new InventoryItem(i_idTX.getText(),i_nameTX.getText(),0f,Double.parseDouble(i_priceTX.getText()),itemimg,Integer.parseInt(i_quantiyTX.getText()) ,p,CatNameTX2.getText());
         }
        else if(state.equals("withoutpormotion"))
        {
            item=new InventoryItem(i_idTX.getText(),i_nameTX.getText(),0f,Double.parseDouble(i_priceTX.getText()),itemimg,Integer.parseInt(i_quantiyTX.getText()) ,CatNameTX2.getText());

        }
        manager.addInventoryItems(state, item);
        i_idTX.setText("");
        i_nameTX.setText("");
        CatNameTX2.setText("");
        i_priceTX.setText("");
        i_quantiyTX.setText("");
        imgLBL.setIcon(defaltimg);
        System.out.println("done");

    }//GEN-LAST:event_ADD_ITEM_BActionPerformed

    

    
    private void backtomenuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomenuBActionPerformed
        managerlayout man=new managerlayout();
        man.show();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_backtomenuBActionPerformed

    private void choiceimgBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceimgBActionPerformed
        // to take the img from pc to lable
        
        JFileChooser file=new JFileChooser();
        FileNameExtensionFilter filter =new FileNameExtensionFilter("images", "png","jpg","gif");
        file.addChoosableFileFilter(filter);
        int RESULT=file.showSaveDialog(null);
        if(RESULT==JFileChooser.APPROVE_OPTION)
        {
            File selected =file.getSelectedFile();
            String imgPath=selected.getAbsolutePath();
            ImageIcon img=new ImageIcon(new ImageIcon(imgPath).getImage().getScaledInstance(imgLBL.getWidth(), imgLBL.getHeight(), Image.SCALE_SMOOTH));
            imgLBL.setIcon(img);
            
           // to take the img from labl to byte array[]
           
            try{
                //catch the img
                File image=new File(imgPath);
                //put it in file input strem to read it 
                FileInputStream fis=new FileInputStream(image);
                //the way i wanna to read by is byte by byte and put max size to it
                byte[] bufer=new byte[1024];
                //creat output stream to have the img in
                ByteArrayOutputStream BAOS=new ByteArrayOutputStream();
                        
                //for loop for read the img in the file stram byte by byte and put it in byte
                //array output straem until it reach to -1 that mean the end of the img
                for(int temp ; (temp=fis.read(bufer))!=-1;)//for seeking 
                {
                    BAOS.write(bufer,0,temp);//put byte array in the BAOS
                }
                itemimg=BAOS.toByteArray();
                
            }catch(Exception ex)
            {
                System.out.println(ex.getMessage());
            }
        }
        else if(RESULT==JFileChooser.CANCEL_OPTION)
        {
            System.out.println("no file selected");
        }
    }//GEN-LAST:event_choiceimgBActionPerformed

    private void add_porBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_porBActionPerformed
        add_pormationform add_a=new add_pormationform();
        add_a.show();
        
    }//GEN-LAST:event_add_porBActionPerformed

    private void i_priceTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_priceTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_priceTXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additemform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additemform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additemform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additemform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additemform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton ADD_ITEM_B;
    private javax.swing.JTextField CatNameTX2;
    private keeptoo.KButton add_porB;
    private keeptoo.KButton backtomenuB;
    private keeptoo.KButton choiceimgB;
    private javax.swing.JTextField i_idTX;
    private javax.swing.JTextField i_nameTX;
    private javax.swing.JTextField i_priceTX;
    private javax.swing.JTextField i_quantiyTX;
    private javax.swing.JLabel imgLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
