/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.Manger_GUI;

import AppPackage.AnimationClass;
import com.restaurant.Manger_Calsses.Manager;
import com.restaurant.Manger_GUI.managerlayout;
import com.restaurant.Manger_GUI.additemform;
import com.restaurant.User_GUI.mainMenu;
import com.restaurant.User_GUI.menu_form;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmo
 */
public class menucontrol extends javax.swing.JFrame {

    /**
     
     */
    AnimationClass ac = new AnimationClass();
    public menucontrol() {
        initComponents();
        this.setLocationRelativeTo(null);
        rest_NameTX.setBackground(new java.awt.Color(0,0,0,1));
        
       // SlideShow();
    }
public void SlideShow()
{
    new Thread(new Runnable() {
            int count = 0;
            @Override
            public void run() {
                try{
                    while(true){
                        switch(count){
                            
                            case 0:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(0, -1080, 20, 10, jLabel3);
                                count++;
                                break;
                        }
                    }
                }
                catch(Exception e){
                    
                }
            }
        }).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        rest_NameTX = new javax.swing.JTextField();
        addmainB = new keeptoo.KButton();
        resetB = new keeptoo.KButton();
        kButton1 = new keeptoo.KButton();
        backtomanager = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 620));
        setSize(new java.awt.Dimension(1080, 620));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resturant Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 160, 200, 26);

        rest_NameTX.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        rest_NameTX.setForeground(new java.awt.Color(255, 255, 255));
        rest_NameTX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        rest_NameTX.setOpaque(false);
        rest_NameTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rest_NameTXActionPerformed(evt);
            }
        });
        getContentPane().add(rest_NameTX);
        rest_NameTX.setBounds(240, 150, 340, 30);

        addmainB.setBorder(null);
        addmainB.setText("Add New Item");
        addmainB.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        addmainB.setkBackGroundColor(new java.awt.Color(255, 0, 51));
        addmainB.setkBorderRadius(30);
        addmainB.setkEndColor(new java.awt.Color(255, 0, 51));
        addmainB.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        addmainB.setkHoverForeGround(new java.awt.Color(153, 0, 0));
        addmainB.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        addmainB.setkIndicatorThickness(0);
        addmainB.setkSelectedColor(new java.awt.Color(0, 0, 0));
        addmainB.setkStartColor(new java.awt.Color(153, 0, 0));
        addmainB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmainBActionPerformed(evt);
            }
        });
        getContentPane().add(addmainB);
        addmainB.setBounds(110, 300, 260, 40);

        resetB.setBorder(null);
        resetB.setText("Reset Main Menu");
        resetB.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        resetB.setkBackGroundColor(new java.awt.Color(255, 0, 51));
        resetB.setkBorderRadius(30);
        resetB.setkEndColor(new java.awt.Color(255, 0, 51));
        resetB.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        resetB.setkHoverForeGround(new java.awt.Color(153, 0, 0));
        resetB.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        resetB.setkIndicatorThickness(0);
        resetB.setkSelectedColor(new java.awt.Color(0, 0, 0));
        resetB.setkStartColor(new java.awt.Color(153, 0, 0));
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });
        getContentPane().add(resetB);
        resetB.setBounds(50, 390, 390, 45);

        kButton1.setBorder(null);
        kButton1.setText("View Main Menu");
        kButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(255, 0, 51));
        kButton1.setkBorderRadius(30);
        kButton1.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton1.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        kButton1.setkHoverForeGround(new java.awt.Color(153, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton1.setkIndicatorThickness(0);
        kButton1.setkSelectedColor(new java.awt.Color(0, 0, 0));
        kButton1.setkStartColor(new java.awt.Color(153, 0, 0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1);
        kButton1.setBounds(40, 490, 410, 45);

        backtomanager.setBorder(null);
        backtomanager.setText("BACK");
        backtomanager.setkBackGroundColor(new java.awt.Color(255, 0, 51));
        backtomanager.setkBorderRadius(0);
        backtomanager.setkEndColor(new java.awt.Color(255, 0, 51));
        backtomanager.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        backtomanager.setkHoverForeGround(new java.awt.Color(153, 0, 0));
        backtomanager.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        backtomanager.setkIndicatorThickness(0);
        backtomanager.setkSelectedColor(new java.awt.Color(0, 0, 0));
        backtomanager.setkStartColor(new java.awt.Color(153, 0, 0));
        backtomanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomanagerActionPerformed(evt);
            }
        });
        getContentPane().add(backtomanager);
        backtomanager.setBounds(0, 0, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/553eed4e-5bda-11e9-bbcc-84176f6dd1e7_image_hires_062817.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 620);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ce63f8fae20206c595a52938c91d9caa.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rest_NameTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rest_NameTXActionPerformed
       
    }//GEN-LAST:event_rest_NameTXActionPerformed

    private void backtomanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomanagerActionPerformed
        managerlayout man =new managerlayout();
        man.show();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtomanagerActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed

        int result=JOptionPane.showConfirmDialog(this, "Are you sure that you wanna reset main menu");
        if(result==0)
        { Manager m=new Manager();
            m.reset();
            JOptionPane.showMessageDialog(this, "reset is done");
        }
    }//GEN-LAST:event_resetBActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        
        The_inventoryform inv=new The_inventoryform();
        inv.show();
        //this.dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

        
        
        
        
                                          

    private void addmainBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmainBActionPerformed
        additemform add_i =new additemform();
        add_i.show();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_addmainBActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menucontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menucontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menucontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menucontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menucontrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton addmainB;
    private keeptoo.KButton backtomanager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton resetB;
    private javax.swing.JTextField rest_NameTX;
    // End of variables declaration//GEN-END:variables
}

