/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.Manger_GUI;

import com.restaurant.Manger_Calsses.Manager;
import com.restaurant.User_GUI.item_panal;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


/**
 *
 * @author mahmoudjoe
 */
public class The_inventoryform extends javax.swing.JFrame {

    /**
     * Creates new form The_inventoryform
     */
    public static int row=0;
    
    public The_inventoryform() {
        initComponents();
        
        //UIManager.put("TabbedPane.contentOpaque", false);
        this.setLocationRelativeTo(null);
        Manager m=new Manager();
        m.viewinventoryitems();
        this.setTitle("5M Restaurant");
        
        for (Map.Entry<String, List> mymap : m.category.entrySet()) {         
                        JPanel panal = new JPanel();

                        List<item_panal> newlist = new ArrayList();
                    newlist = mymap.getValue();
     //mahmoud//               
                    if((newlist.size()%2)!=0)
                        row=(newlist.size()+1)/2;
                    else
                        row=(newlist.size())/2;
                     panal.setLayout(new GridLayout(row,2));
    //mahmoud//                 
                     
                     JScrollPane pane = new JScrollPane(panal);
                    for (int i=0;i<newlist.size();i++) {
                        panal.add(newlist.get(i));
                    }
                    JLabel label = new JLabel("");
                label.setIcon(new ImageIcon("E:\\imageDB\\menumenucopy.jpg"));/*
                 label.setBounds(0, 0, 817, 658);
                 pane.add(label);*/
                     jTabbedPane1.addTab(mymap.getKey(),pane);  
                     
                    // jTabbedPane1.setLayout(new GridLayout(3,5));
                   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 620));
        getContentPane().setLayout(null);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(120, 0, 830, 620);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/food-table-relisted.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(The_inventoryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(The_inventoryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(The_inventoryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(The_inventoryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new The_inventoryform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables


}
